version: '2'
services:
  web_1:
    build:
      context: web
      args:
        - DIR=web_1 
  web_2:
    build:
      context: web
      args:
        - DIR=web_2
  load_balancer:
    build:
      context: load_balancer
    ports:
      - "8080:80"
