version: '2'
services:
  web_1:
    build:
      context: web
      args:
        - DIR=web_1 
    ports: 
      - "8081:80"
  web_2:
    build:
      context: web
      args:
        - DIR=web_2
    ports:
      - "8082:80"
